name: zammad-docs

# Controls when the workflow will run.
on:

  # Allow the workflow to be reusable.
  workflow_call:
    inputs:
      requirements_path:
        description: Path to the `requirements.txt`, relative to the repository root.
        required: false
        default: requirements.txt
        type: string
      docs_path:
        description: Path to the documentation directory, relative to the repository root.
        required: false
        default: .
        type: string
      system_dependencies:
        description: Optional list of system dependencies to install via `apt` command, separated by spaces.
        required: false
        default: 'gettext'
        type: string
      python_version:
        description: The version of Python binary to use.
        required: false
        default: '3.7'
        type: string
      repository:
        description: The source repository name, in case it differs from the current one.
        required: false
        default: ${{ github.repository }}
        type: string
      ref:
        description: The source repository reference, in case it differs from the current one.
        required: false
        default: ${{ github.ref }}
        type: string

jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        fetch-depth: 50

    - name: Install System Dependencies
      shell: bash -eux {0}
      run: |
        sudo apt-get -q -y update
        sudo apt-get -q -y install ${{ inputs.system_dependencies }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install Python Dependencies
      shell: bash -eux {0}
      run: |
        python -m pip install --upgrade --no-cache-dir pip setuptools
        python -m pip install --upgrade --no-cache-dir pillow mock==1.0.1 'alabaster>=0.7,<0.8,!=0.7.5' commonmark==0.9.1 recommonmark==0.5.0 'sphinx<2' 'sphinx-rtd-theme<0.5' 'readthedocs-sphinx-ext<2.3' 'jinja2<3.1.0'
        python -m pip install --exists-action=w --no-cache-dir -r ${{ inputs.requirements_path }}

    - name: Debug Configuration
      shell: bash -eux {0}
      run: cat conf.py

    - name: Build Documentation
      shell: bash -eux {0}
      run: |
        cd ${{ inputs.docs_path }}
        python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
        # python -m sphinx -T -E -b readthedocssinglehtmllocalmedia -d _build/doctrees -D language=en . _build/htmlzip
        python -m sphinx -T -E -b epub -d _build/doctrees -D language=en . _build/epub

    - name: Upload html Artifact
      uses: actions/upload-artifact@v3
      with:
        name: html
        path: ${{ inputs.docs_path }}/_build/html/

    # - name: Upload htmlzip Artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: htmlzip
    #     path: ${{ inputs.docs_path }}/_build/htmlzip/

    - name: Upload epub Artifact
      uses: actions/upload-artifact@v3
      with:
        name: epub
        path: ${{ inputs.docs_path }}/_build/epub/
